markdown : redcarpet
highlighter : 'pygments'

title: DCU website

url: http://dcuenot.github.io

permalink: /:year/:month/:day/:title/

author:
    name: Damien Cuenot
    email: damien.cuenot@live.com
    github: dcuenot
    twitter: cdams86
    linkedin: cuenotdamien
    gravatar: http://www.gravatar.com/avatar/bd53e2936f38a210b8e371b781a7bd40.png

comments:
    provider: disqus
    disqus:
        short_name: dcuenot
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-61527984-1'
        domain: 'dcuenot.github.io'
        
        
categories :
    - Tech-stuff
    - Learning
    - Random

navigation :
    - title : 'Whoami'
      url : '/whoami.html'
      icon: 'icon-user'

    - title : 'Tech-stuff'
      url : '/index.html'
      icon : 'icon-home' 

    - title : 'Présentations'
      url : '/presentation/index.html'
      icon : 'icon-leaf'

    - title : 'Random'
      url : '/random/index.html'
      icon : 'icon-chevron-right'